### ISSUE TITLE
Change default data directory from 'bitcoin' to 'bitcoin-abc'

### ISSUE THREAD

**Issue by cryptoapi** [Bitcoin-ABC/bitcoin-abc#32] opened 2017-07-27 00:37 UTC
or to something else.

**Comment by cryptoapi** [comment] 2017-07-27 23:26
You can change default directories in function **boost::filesystem::path GetDefaultDataDir(){..}**
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/util.cpp#L470

to something like - "bitcoinabc",

original lines - 
// Windows
    return GetSpecialFolderPath(CSIDL_APPDATA) / "Bitcoin";
// Unix
return pathRet / ".bitcoin";

to
return GetSpecialFolderPath(CSIDL_APPDATA) / "BitcoinAbc";
return pathRet / ".bitcoinabc";

etc.

**Comment by deadalnix** [comment] 2017-07-27 23:27
Yes, I want to do that at the same time we change the magic. So the software will be able to take existing data in .bitcoin and dump them in the new folder with the new magic. Doing both at once will limit disruption.

**Comment by abelgo** [comment] 2017-07-31 14:30
Do you like you could solve that problem by using a sym links or an install script of some kind, on osx it just destroys any existing core clone setup by using all the same paths and binary names.  On a unix release it required some creative re-naming of the binaries then a bit of sym link setup to the existing block core directory structure.

**Comment by ftrader** [comment] 2017-07-31 15:52
The ABC client should not use the same data directory as another which may want to change their data format or even move their data to another location. Such symlinking may be adequate to do as a resource-saving measure for a personal installation, but it is not suitable as a safe way of wide deployment.

Where conflicts with existing installed software exist they should be resolved such that ABC can be operated independently, and data migrations steps offered to the user where possible.

**Comment by Antontulaa** [comment] 2017-08-16 22:21
Hi ! I password from wallet ABS bitcoin cache. How to recover the password. Please help!

**Comment by Antontulaa** [comment] 2017-08-16 22:23
Hi ! I lost the password from wallet ABS bitcoin cache. How to recover the password. Please help!

**Comment by schancel** [comment] 2018-04-25 22:09
Duplicate of #141

**Closed by schancel** 2018-04-25 22:09 UTC
