### ISSUE TITLE
Wrong transaction date when using importmulti

### ISSUE THREAD

**Issue by jimukgb** [Bitcoin-ABC/bitcoin-abc#128] opened 2017-12-01 00:36 UTC
#### If so, please list the steps to reproduce below:

1. importing multiple private keys with importmulti on testnet
2. check corresponding transaction under Transactions tab
3. the date is wrong and appears random i.e. neither the date of the block in which the transaction was included, nor the current time of importing

### Expected behaviour
I expect the date of transactions to be either when they were sent/received or that of the bock time especially for imported private keys where exact timing would not be otherwise available

### Actual behaviour
It appears to record the transaction with a random date

### What version of bitcoin-abc are you using?
16.1

### Machine specs:
- OS: Windows 7
- CPU: Core i7
- RAM: 8 GiB
- Disk size: 1 TB
- Disk Type (HD/SDD): HD

**Comment by jasonbcox** [comment] 2018-06-29 23:38
Duplicate of #80

**Closed by jasonbcox** 2018-06-29 23:38 UTC
Labels: duplicate
