### ISSUE TITLE
Bitcoin ABC uses the same registry path on Windows as Bitcoin Core

### ISSUE THREAD

**Issue by eg-be** [Bitcoin-ABC/bitcoin-abc#77] opened 2017-08-25 07:20 UTC
### Describe the issue
On Windows, Bitcoin Core and Bitcoin ABC both store their settings by default in the registry at `Computer\HKEY_CURRENT_USER\Software\Bitcoin\Bitcoin-Qt`. This actually prevents running Bitcoin Core and Bitcoin ABC on the same machine, without taking extra care: The key `strDataDir` stores the path to the datadirectory. The local copy of the blockchain will get corrupted if you run both (not even parallel, but sequentially) and do not explicitly pass the option `datadir`.

#### If so, please list the steps to reproduce below:
1. Install Bitcoin Core, choose some data directory
2. Check the registry, it is stored in strDataDir
3. Install Bitcoin ABC, it will silently also use that strDataDir

### Expected behaviour
Bitcoin ABC should have its separate registry path.

### Actual behaviour
Bitcoin ABC uses the same registry path as Bitcoin Core

### What version of bitcoin-core are you using?
Bitcoin ABC Version v0.14.6.0-a46e63c (64-Bit)

### Machine specs:
- OS: Windows 10, 64bit (en)

**Comment by bacoboy** [comment] 2017-10-21 17:00
dupe of #32 ?

**Comment by eg-be** [comment] 2017-10-22 11:31
Related, but probably not a dupe: #32 is about the configuration **directory** (a path on the filesystem). This issue here is about an entry in the windows **registry**.

**Comment by bacoboy** [comment] 2017-10-22 23:47
Perhaps not specifically, but feels like the intent of all these issues to for the ABC node to be runnable in parallel to the core node which is why it smelled like a dupe.

**Comment by schancel** [comment] 2017-12-20 04:14
Closing as a dup of #40

**Closed by schancel** 2017-12-20 04:14 UTC
