### ISSUE TITLE
Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.

### ISSUE THREAD

**Issue by i3bitcoin** [Bitcoin-ABC/bitcoin-abc#65] opened 2017-08-04 13:58 UTC
Hi,

I'm trying to set up Bitcoin-abc wallet on my Ubuntu 16.04 server. After a full sync I'm receiving this message:
Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.

And can't connect the wallet using rpc.

Does someone have this issue before?

I've tried to reload the wallet several times, the message disappears till the new block is mined.

**Comment by arnuschky** [comment] 2017-08-04 14:16
Same here. Sometimes goes away when adding known abc nodes, but comes back.

**Comment by i3bitcoin** [comment] 2017-08-04 14:22
I'm syncing at the moment, we'll see how much I have now)

**Comment by cryptoapi** [comment] 2017-08-04 16:18
As temporary solution, you need to change -

https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/validation.cpp#L1163

From
`if (pindexBestForkTip ||
        (pindexBestInvalid &&
         pindexBestInvalid->nChainWork >
             chainActive.Tip()->nChainWork +
                 (GetBlockProof(*chainActive.Tip()) * 6))) {`

To
`if (pindexBestForkTip) `


Also change 

https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/net.h#L65
MAX_OUTBOUND_CONNECTIONS = 100; 
MAX_ADDNODE_CONNECTIONS = 100;

recompile it .

And add in bitcoin.conf 

addnode=13.126.32.103:8333
addnode=47.94.56.232:8333
addnode=144.76.220.17:9090
addnode=39.108.71.254:8333
addnode=52.63.175.61:8333
addnode=97.113.45.103:8333
addnode=71.127.43.68:8333
addnode=52.77.223.113:8333
addnode=51.15.78.11:8333
addnode=5.135.180.61:8333
addnode=46.233.43.155:8333
addnode=13.210.30.22:8333
addnode=176.24.198.205:8334
addnode=69.55.64.221:8333
addnode=47.91.197.178:8333
addnode=72.190.79.138:8333
addnode=45.33.14.27:8333
addnode=13.55.131.240:8333
addnode=76.118.98.204:8333
addnode=35.154.149.128:8333
addnode=52.221.227.157:8333
addnode=54.179.133.79:8333
addnode=83.163.223.145:8333
addnode=80.216.4.252:8333
addnode=71.93.206.181:8333
addnode=147.91.82.116:8333
addnode=188.68.38.210:8333
addnode=100.4.108.100:8333
addnode=98.206.255.202:8333
addnode=13.126.155.63:8333
addnode=122.228.96.58:8333
addnode=178.21.118.33:8333
addnode=39.108.100.122:8333
addnode=47.94.57.128:8333
addnode=47.94.57.121:8333
addnode=47.94.45.184:8333
addnode=47.93.120.133:8333
addnode=47.94.47.152:8333
addnode=39.108.107.120:8333
addnode=47.94.57.156:8333
addnode=68.11.92.58:8333
addnode=54.66.222.15:8333
addnode=34.253.24.13:8333
addnode=163.172.4.66:8333
addnode=108.61.205.173:8333
addnode=54.238.171.233:8333
addnode=34.227.47.255:8333
addnode=178.238.233.12:8333
addnode=69.172.174.21:8333

**Comment by deadalnix** [comment] 2017-08-04 19:51
This situation will improve as network splits better. Core is already taking step in that direction by banning node using the cash service bit, and we are as well by starting a process to change the magic used in the network protocol.

**Comment by arnuschky** [comment] 2017-08-04 20:26
Thanks. I patched the daemon, but I am resyncing so I can't see any effect yet.

**Comment by nomnombtc** [comment] 2017-08-04 21:02
I've setup an electrumx server for BCC and also sometimes have this issue, it results in errors when people try to send transactions...:

`INFO:ElectrumX:[17468] sendrawtransaction: Safe mode: Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade.`

Here: https://en.bitcoin.it/wiki/Alerts#Safe_mode it says the safemode can be disabled with `-disablesafemode` maybe this will work without modifying code as temp workaround, going to try this now ...

**Comment by i3bitcoin** [comment] 2017-08-05 11:46
Thanks for your help. I've resynced the blockchain, it shows that message again, but rpc seems to be online all the time.

**Comment by c0deright** [comment] 2017-08-07 08:53
Duplicate of https://github.com/Bitcoin-ABC/bitcoin-abc/issues/59

**Comment by danny91** [comment] 2017-08-07 12:00
@cryptoapi addnode=176.24.198.205:8334 could you change that to;

addnode=bcc.arihanc.com:8334

Thanks! :) (i'm arihanc)

**Comment by ftrader** [comment] 2017-08-07 13:17
Code change implemented on Phabricator and up for review:
https://reviews.bitcoinabc.org/D439

I've run the tests, but if anyone is willing they can download the raw patch, apply it and run with it too until such time as it gets approved.

**Comment by schancel** [comment] 2017-12-20 03:50
Thank you for reporting this.  It should now be resolved.  Please reopen if it's still an issue.

**Closed by schancel** 2017-12-20 03:50 UTC
