### ISSUE TITLE
port & rpcport parameter in conf file don't take effect

### ISSUE THREAD

**Issue by huahuayu** [Bitcoin-ABC/bitcoin-abc#314] opened 2019-03-29 03:45 UTC
### Describe the issue
I have a config file as below which I specific port & rpcport , but they don't take effect.   

### steps to reproduce the issue:  
**step1:**
I have run bitcoin core mainnet & testnet in default ports, so I differentiate bitcoin abc ports in config file`/home/bch/.bitcoin/bitcoinabc_testnet3.conf`:  

**rpcport=17332  
port=7332
datadir=/mnt/data/bitcoinabc**  

```
# Generated by https://jlopp.github.io/bitcoin-core-config-generator/

# This config should be placed in following path:
# /home/bch/.bitcoin/bitcoinabc_testnet3.conf

# [core]
# Specify the location of the configuration file. To use non-default location, create a default location config file containing this setting.
conf=/home/bch/.bitcoin/bitcoinabc_testnet3.conf
# Specify a non-default location to store blockchain and other data.
datadir=/mnt/data/bitcoinabc

# [debug]
# Enable debug logging for all categories.
#debug=1
# Log IP Addresses in debug output.
#logips=1
# Run this node on the Bitcoin Test Network.
testnet=1

# [network]
# Listen for incoming connections on non-default port.(default: 8333 or testnet: 18333)
port=17333

# [rpc]
# Accept command line and JSON-RPC commands.
server=1
# Accept public REST requests.
rest=1
# RPC user
rpcuser=rpcuser
# RPC password
rpcpassword=rpcpass
# RPC port(default:8332 or testnet:18332)
rpcport=17332
# RPC allow ip (allow all)
rpcallowip=0.0.0.0/0
# RPC bind
#rpcbind=127.0.0.1
# get all transaction
txindex=1

# [Sections]
# Most options automatically apply to mainnet, testnet, and regtest networks.
# If you want to confine an option to just one network, you should add it in the relevant section.
# EXCEPTIONS: The options addnode, connect, port, bind, rpcport, rpcbind and wallet
# only apply to mainnet unless they appear in the appropriate section below.

# Options only for mainnet
[main]

# Options only for testnet
[test]

# Options only for regtest
[regtest]
```

**step2:**
run bitcoind and get error:
``` bash
$ bitcoind --version
Bitcoin ABC Daemon version v0.19.2.0-816dbd915

$ bitcoind -conf=/home/bch/.bitcoin/bitcoinabc_testnet3.conf
Error: Unable to start HTTP server. See debug log for details.
```

the debug.log file: 
error reason: Binding RPC on address 0.0.0.0 port 18332 failed(because bitcoin core is using it) 
```
2019-03-29T03:17:16Z Bitcoin ABC version v0.19.2.0-816dbd915
2019-03-29T03:17:16Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2019-03-29T03:17:16Z Warning: Config setting for -port only applied on test network when in [test] section.
2019-03-29T03:17:16Z Warning: Config setting for -rpcport only applied on test network when in [test] section.
2019-03-29T03:17:16Z Checkpoints will be verified.
2019-03-29T03:17:16Z Assuming ancestors of block 00000000000002cb911c0a756a24c2fe6c1a29acaede3569ce430b95d8ff012d have valid signatures.
2019-03-29T03:17:16Z Setting nMinimumChainWork=000000000000000000000000000000000000000000000043cb761ba833f844c5
2019-03-29T03:17:16Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2019-03-29T03:17:16Z Using RdRand as an additional entropy source
2019-03-29T03:17:16Z Default data directory /home/bch/.bitcoin
2019-03-29T03:17:16Z Using data directory /mnt/data/bitcoinabc/testnet3
2019-03-29T03:17:16Z Using config file /home/bch/.bitcoin/bitcoinabc_testnet3.conf
2019-03-29T03:17:16Z Using at most 125 automatic connections (65535 file descriptors available)
2019-03-29T03:17:16Z Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
2019-03-29T03:17:16Z Using 32 MiB out of 32 requested for script execution cache, able to store 1048576 elements
2019-03-29T03:17:16Z Using 6 threads for script verification
2019-03-29T03:17:16Z scheduler thread start
2019-03-29T03:17:16Z libevent: getaddrinfo: address family for nodename not supported
2019-03-29T03:17:16Z Binding RPC on address :: port 18332 failed.
2019-03-29T03:17:16Z Binding RPC on address 0.0.0.0 port 18332 failed.
2019-03-29T03:17:16Z Unable to bind any endpoint for RPC server
2019-03-29T03:17:16Z Error: Unable to start HTTP server. See debug log for details.
2019-03-29T03:17:16Z Shutdown: In progress...
2019-03-29T03:17:16Z scheduler thread interrupt
2019-03-29T03:17:16Z Shutdown: done
```

**problem summary**:
I have specific 17332 as the rpcport, why bitcoinabc don't use my config?

**Comment by huahuayu** [comment] 2019-03-29 03:46
@schancel

**Comment by jasonbcox** [comment] 2019-03-29 21:40
Looks like a duplicate of #312

**Comment by jasonbcox** [comment] 2019-03-29 22:38
Please read this comment in the config you provided carefully, as it answers your question:
```
# [Sections]
# Most options automatically apply to mainnet, testnet, and regtest networks.
# If you want to confine an option to just one network, you should add it in the relevant section.
# EXCEPTIONS: The options addnode, connect, port, bind, rpcport, rpcbind and wallet
# only apply to mainnet unless they appear in the appropriate section below.****
```
Similar guidance and an example may be found in 0.18.8's release notes: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.18.8.md

Upon testing this myself, I confirmed that there is a warning provided in the logs for this as well.

The fix you're looking for is to apply `rpcport=17332` only in the [test] section for the testnet config.  This way, you can provide a different rpcport value for the mainnet config explicitly.

**Closed by jasonbcox** 2019-03-29 22:38 UTC

**Comment by dmitry537** [comment] 2020-07-10 07:25
I have a similar problem, bitcoin abc ignores rpc port. 
Here is my config:
```
datadir=/opt/bch
blocksdir=/opt/bch
testnet=1
txindex=1
server=1
rpcuser=bchUser
rpcpassword=1p2a3s

# Options only for mainnet
[main]

# Options only for testnet
[test]
port=19333
rpcport=19332

# Options only for regtest
[regtest]
```


What am I doing wrong?

**Comment by jasonbcox** [comment] 2020-07-10 17:00
You haven't really described what behavior you're experiencing. Please open a new issue with log output, expected behavior, and any command line arguments you're using to run bitcoind.  You'll get faster and more directed help that way.
