### ISSUE TITLE
[Bitcore] Address Index Does not Work as Intended

### ISSUE THREAD

**Issue by prusnak** [Bitcoin-ABC/bitcoin-abc#43] opened 2017-08-01 12:52 UTC
For example for this address: `1HuiNCrXDEDHeUkKZds1EMPvwW5ejwNeN2`

When running Bitcore for Bitcoin, it shows correctly the following transaction: `86d813bdf37a27da0b210d41003da9556327e74650bd53bd068d30600fb54a8a`

But running Bitcore for Bitcoin Cash it shows no transactions.

(I am leaving this issue here, because fork which contains Bitcore patches - https://github.com/bitprim/bitcoin-abc - does not have issues enabled.

**Comment by prusnak** [comment] 2017-08-01 12:53
@hanchon Have you ever run your code in production? Can you test?

// cc @runn1ng

**Comment by runn1ng** [comment] 2017-08-01 13:03
it's terrible to test and do everything at the very last possible time with little time for testing, but I guess that's the way of bitcoin cash

**Comment by prusnak** [comment] 2017-08-01 13:52
Oddly enough, I am not able to reproduce after we copied the Blockchain from vanilla Bitcore.

**Comment by runn1ng** [comment] 2017-08-01 13:55
yep, cannot reproduce. Let's wait until ABC miners mine a few blocks, if that happens.

**Comment by runn1ng** [comment] 2017-08-01 19:49
yep, it just did it again

https://bch-bitcore2.trezor.io/address/1GqSZsZhppf2XzqkRvuK7u8wkUCdcmfwXr

Seemse there is bitcore running here without these issues, but maybe I looked at wrong blocks

http://blockdozer.com/insight/address/1GqSZsZhppf2XzqkRvuK7u8wkUCdcmfwXr

**Comment by prusnak** [comment] 2017-08-01 21:04
You can spot the problem when you see an address with negative balance as stated in previous comment. The negative balance also helps to identify which TX is missing from address index.

I just found another bug, this time in Blockdozer:

http://blockdozer.com/insight/address/1FzWbC2fkzKXX8ASdx2QuBbwc9MSS77gER

Correct balance on our server:

https://bch-bitcore2.trezor.io/address/1FzWbC2fkzKXX8ASdx2QuBbwc9MSS77gER

So the issue is not deterministic :-/

**Comment by runn1ng** [comment] 2017-08-01 21:50
just for info (for debugging etc)

the patchset from the bitprim repo is the same one as the one in this PR, just it's renamed and rebased in the PR

https://github.com/Bitcoin-ABC/bitcoin-abc/pull/34

we run the version built here (the same patches, on top of 0.14.6 again, plus some docker stuff for building static files deterministically)

https://github.com/satoshilabs/bitcoin-abc

You can compare it with bitcoin core with bitcore patches (the reformatting changes do that more complicated, but that is what it is) - https://github.com/satoshilabs/bitcoin

I don't really know where might the issue be,  it seems everything should be working, but it isn't. Some blocks just don't save the txs into the address index.

I will try the qa tests

**Comment by prusnak** [comment] 2017-08-01 21:59
Can confirm that code checkouted from https://github.com/satoshilabs/bitcoin-abc/tree/0.14.6-bitcore and  https://github.com/bitprim/bitcoin-abc/tree/tag0.14.6-bitcore is the same (modulo `/contrib/docker_build` directory which is present only in our fork).

**Comment by runn1ng** [comment] 2017-08-02 10:04
I have tried the qa pull tester for address index (that were added in the patch) and they work as intended.

(Some of the tests still fail, but that doesn't seem to be the fault of the bitcore patches - https://github.com/Bitcoin-ABC/bitcoin-abc/issues/52 )

**Comment by prusnak** [comment] 2017-08-02 11:06
Hm, it seems that index is decaying in time.

Yesterday I wrote that TX count is 131 vs 133, today it is 129 vs 133 :-/

**Comment by saleemrashid** [comment] 2017-08-02 11:12
For future reference, since the index is decaying:

```diff
--- blockdozer.json
+++ trezor.json
@@ -1,16 +1,20 @@
 {
     "addrStr": "1FzWbC2fkzKXX8ASdx2QuBbwc9MSS77gER",
-    "balance": 2.38923735,
-    "balanceSat": 238923735,
-    "totalReceived": 313.07100158,
-    "totalReceivedSat": 31307100158,
-    "totalSent": 310.68176423,
-    "totalSentSat": 31068176423,
+    "balance": 0.100675,
+    "balanceSat": 10067500,
+    "totalReceived": 315.54300158,
+    "totalReceivedSat": 31554300158,
+    "totalSent": 315.44232658,
+    "totalSentSat": 31544232658,
     "unconfirmedBalance": 0,
     "unconfirmedBalanceSat": 0,
     "unconfirmedTxApperances": 0,
-    "txApperances": 129,
+    "txApperances": 133,
     "transactions": [
+        "92bd22a4ee839c0e8ce11bd0a4d30b1703d0147558af3fbf5eea533c976aa0ef",
+        "e1bb4c5d79a1dc94471d880d41569d909636905bf8e407bf8afa297af6268325",
+        "000bcb8f86c96b60263fc354b9cec4424a487426467b35bafa2b23fed4d09e5d",
+        "50f30b0826f66adce0d24dcfb0d0bf6b9b0f041feb523f728acb25f3f76147a4",
         "eb94cbf4a39c2463a9241f9f9e8d8fcfb9d047a67c3d3dd6cb13e302a40c0e85",
         "ac29a9bf5a17d778eaa8c2f68240e5cc95b084b9e273c60903ffaae9f2f02526",
         "33482e765fb5803b0236cfb5b7a9e3cc34ded9df13979cd1da4ce939656b5a56",
```

**Comment by prusnak** [comment] 2017-08-02 15:08
@hanchon ping?

**Comment by hanchon** [comment] 2017-08-02 15:49
I'm following this issue and looking at the code to see if something is wrong. I created the same issue at the bitprim/bitcoin-abc repository. If I find something that needs to be changed, I'll update that repository

**Comment by prusnak** [comment] 2017-08-02 15:51
Who is running blockdozer? Is it you @hanchon ?

**Comment by prusnak** [comment] 2017-08-02 16:31
Found workaround:

```
bitcoin-cli invalidateblock XXX
bitcoin-cli reconsiderblock XXX
```

where XXX is the first known broken block.

A reorg is performed and this will fix the address index.

**Comment by TrompoMax** [comment] 2017-08-02 16:44
You guys are Heros.  Thank you for doing what you're doing.

**Comment by runn1ng** [comment] 2017-08-02 17:08
@prusnak do you plan to do this periodically after every block? Do you have any idea why it works on reconsiderblock but doesn't work on normal block? Maybe it has something to do with the UAHF rules? (Wild guesses!)

I was a little busy today, but I will try to run regtest and bombard it with transactions and blocks, seeing if I can reliably replicate the issue

**Comment by dlawnroac** [comment] 2017-08-02 18:35
@runn1ng I'm not sure if it can help you with replicating the problem, but:
- yesterday I used TREZOR's "Claim BCH" feature, which resulted in transaction that was included in BCH block nr. 478564
- just after claiming the BCH, I could see the correct BCH amount displayed in TREZOR BCH Web Wallet
- shortly after that you disabled the web wallet because of this issue, so I don't know what was displayed there after block 478564 was mined, however:
- today in the afternoon, while block 478570 was the last mined, I noticed the https://bch-bitcore2.trezor.io/ displayed that my (only) BCH address was now EMPTY
- now, when the block 478573 is the last mined, I noticed it is fixed and correct BCH amount is once again indicated (is that result of that invalidateblock / reconsiderblock workaround mentioned by @prusnak ?)

Anyway, if you think it would help you investigate I can somehow send you the address and the transaction ID where I noticed this problem (I just don't want to simply post it publicly here to GitHub for everyone to see)

**Comment by prusnak** [comment] 2017-08-02 18:39
@dlawnroac what you are describing are just symptoms of our investigating process and are not related to bug itself

**Comment by prusnak** [comment] 2017-08-02 18:40
We already isolated the issue and are testing the fix!

**Comment by jhoenicke** [comment] 2017-08-02 18:42
Not sure if it can cause this, but I noticed that `ConnectBlock` in validity.cpp does the changes to the address and spent index also when `fJustCheck` is true, which it shouldn't.

**Comment by prusnak** [comment] 2017-08-02 18:53
Yes, that is one piece of the puzzle.

Here is fix by Jan which fixes it all (hopefully): https://github.com/satoshilabs/bitcoin-abc/commit/5337f8f210eaa34d1212103f700698dd4989f479

We are testing it right now ...

**Comment by schancel** [comment] 2017-12-20 03:35
Is this still an issue?

**Comment by karel-3d** [comment] 2017-12-20 05:01
Nope, this is already solved, you can close this

**Comment by schancel** [comment] 2017-12-20 05:44
Great, thank you!

**Closed by schancel** 2017-12-20 05:44 UTC
