### ISSUE TITLE
QR-Code useability, address format

### ISSUE THREAD

**Issue by theRealBitcoinClub** [Bitcoin-ABC/bitcoin-abc#197] opened 2018-04-24 16:23 UTC
### Describe the issue
Scanning a QR code containing the new CashAddress format takes more time and patience by the customer. 

That makes QR-Codes in CashAddress format atleast unusable for us. We are using the old format, and we see that we could even improve the old format to make the process easier for the user.

CashAdress: bitcoincash:qrme8p4xhs47cpark2kttcgxgfh0a09udcduukktmj?amount=0.0003
Original: bitcoincash:1Pa4dfgrc1X34bLxWwA1y986yQBEpo4YtN?amount=0.0003
Improved: bch:1Pa4dfgrc1X34bLxWwA1y986yQBEpo4YtN?a=0.0003

You can create QR codes for these addresses on https://www.qrcode-monkey.com/ and then realize the difference yourself. The QR code images get more complex the more information they contain.

### Can you reliably reproduce the issue?
Yes, you can scan various QR-codes and feel the difference, you also have to use different light environments and different devices (with broken screen as well).

#### If so, please list the steps to reproduce below:
1. Check the attached images
2. Zoom in to 150%
3. Open your wallet and scanner and scan the Small Blind from left to right
4. Scan with slightly shaking hands (as this is what people do)
5. Repeat the scan 5 times for Gerardo and 5 times for Jose and feel the difference

![poker-sheet-gerardo](https://user-images.githubusercontent.com/35400618/39199947-06e9c1d6-47eb-11e8-9ec9-f642b2b95c20.png)
![poker-sheet-jose](https://user-images.githubusercontent.com/35400618/39199948-070a5c2a-47eb-11e8-8048-d63493e03af7.png)

### Expected behaviour
The QR-Code scanning of the improved address format should be faster or at the same speed as the scanning time of the original address format.

### Actual behaviour
The process of scanning a QR-Code with the CashAddress format is significantly slower.

**Comment by jasonbcox** [comment] 2018-04-24 18:31
The QR code scanner I'm using has no perceivable difference between any of the QR codes provided, so I cannot reproduce this issue.  It's likely an issue with your QR code scanner, the QR code generation, or both.

I'm no QR code expert, but doesn't having super tiny dots on these QR codes increase the error rate significantly?  This may be affecting your ability to scan.

**Comment by schancel** [comment] 2018-04-25 22:26
This does seem like an issue with the qr code scanner and/or the wallet handling of cashaddresses. Changing back to the legacy address isn't feasible.  I'm closing this issue based on that.

**Closed by schancel** 2018-04-25 22:26 UTC

**Comment by theRealBitcoinClub** [comment] 2018-04-28 15:27
@jasonbcox Hi Jason, thank you for taking this issue partially seriously. First i would like to tell you that there are various ways to verify that this issue is reality.

The most easy way to verify this issue even without scanning is the following way:
1. Go to https://www.qrcode-monkey.com/
2. Create a QR code containing just one word
3. Watch the image

Now change the content of the QR code to several words, create it again and watch the difference.

You will see a more complex image.

A more complex image means -> more processing time

**Comment by theRealBitcoinClub** [comment] 2018-04-28 15:38
https://pbs.twimg.com/media/Db4VB8XX4AE_yY5.jpg:large
