### ISSUE TITLE
Bitcoin-abc missing transactions

### ISSUE THREAD

**Issue by maxvandl** [Bitcoin-ABC/bitcoin-abc#396] opened 2020-06-26 15:29 UTC
Hello!

I having a problem with bitcoin-abc
I have node abc-node  v0.21.9
Sometimes after random period oа time my node doesn't see new transactions for address.
Adress added watch only (without import of private key)

**Comment by jasonbcox** [comment] 2020-09-24 20:42
Hey, we're going to need more information in order to investigate. I'm closing this for now since the version is old.  Feel free to reopen with specific reproduction steps.

**Closed by jasonbcox** 2020-09-24 20:42 UTC
