### ISSUE TITLE
Is there any replay-protections for the fork of 7:06pm (UTC)

### ISSUE THREAD

**Issue by mutalisk999** [Bitcoin-ABC/bitcoin-abc#115] opened 2017-11-13 11:42 UTC

**Comment by davidmann4** [comment] 2017-11-13 13:15
you do not any, there are not 2chains like in a fork where people want 2 versions of the coin. 

in this case the old chain is dead and a new one is used by everone. hardforks happen all the time. Nothing to worry about. 

It's Patchday.

**Comment by rcawston** [comment] 2017-11-18 16:20
Annnnd..... you were wrong! Surprise surprise, you can't predict the future and so clearly should have built-in replay protection.

**Comment by phzi** [comment] 2017-11-18 16:25
And... surprise surprise, @davidmann4 was wrong.  If you can't predict the future, you really should have included replay protection.  I can't honestly see how anyone with half a brain didn't see this chainsplit coming.

**Comment by ftrader** [comment] 2017-11-19 13:17
Anyone can split a chain retroactively without replay protection and with intent to disrupt.

If there is chainsplit (I assume @phzi  is talking about "Bitcoin Clashic") - can someone point to a block explorer or exchange that shows it?

We have no data to indicate Clashic has any significant activity that could be deemed a threat to the main chain. If it's not mined with more hashpower than the main chain, it's about as much to worry about as some orphan block - i.e. not at all.

I recommend this issue be closed.

**Comment by phzi** [comment] 2017-11-19 17:32
@ftrader that's honestly ridiculous. "Anyone can split a chain retroactively without replay protection and with intent to disrupt." Is essentially pure nonsense.  

Bitcoin-ABC created a new fork without replay protection when it was nearly 100% gaurentees that the original chain would survive.  Bitcoin Clashic didn't fork the chain, the "new" BCH is the fork.

Any hard-fork should ALWAYS have replay protection.

A block explorer: http://satoshistruevision.com/#block:last

Clearly there is significant mining activity, and many users have probably already lost their coins on the original chain due to the BCH developer's wrecklessness.

Close the issue? Ya, let's not reflect on bad decisions like EDA and no replay protection when DAA was introduced. /s. The lack of replay protection on the BCH fork is clearly going to be ongoing issue.

**Comment by jli225** [comment] 2017-11-19 20:14
@phzi Don't tell lies and don't be abusive to others here. Enjoy your anti-hardfork egos elsewhere.

As @ftrader said, this issue should be closed because the premise it's based on is nothing but some infamous propaganda and information spread by BCore.

**Comment by phzi** [comment] 2017-11-19 20:34
@jli225 if you're going to accuse someone of lieing in a git issue, you better show some proof.  You've so far failed at both tech skills and people skills.

Where are your code commits or review notes anyway? Oh wait... no tech skills or people skills, got it.

Hard-forking without replay protection has 100% already caused the loss of funds on the original chain due to tx replay. Takes 5 seconds on a block explorer to see this.

**Comment by NiKiZe** [comment] 2017-11-19 22:21
@phzi if what you are claiming is true, that all forks should have replay protection. How come that there are more hardforks in bitcoins history without any kind of replay protection, then with?

And yes there have been several forks in Bitcoins history, the only difference is if someone continue to mine on the old chain or not. And if anyone does continue to mine on the legacy chain, the issue is entirely theirs to cope with. (The only discussion we might want to have is if replay protection should be implemented on a minority chain, but the result in this case the same.)

**Comment by phzi** [comment] 2017-11-19 22:50
@NiKiZe: There has only been one only one hard-fork in bitcoin's history AFAIK, and that was when Satoshi was still around (when the NOP op codes were added).  What forks are you talking about?

**Closed** 2017-11-19 23:02 UTC
