### ISSUE TITLE
configure: error: libdb_cxx headers missing when installing on mac

### ISSUE THREAD

**Issue by hiroki-money** [Bitcoin-ABC/bitcoin-abc#252] opened 2018-09-07 03:23 UTC
### Describe the issue
That error as title occurred when installing on mac following [build-osx.md](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/build-osx.md)

Specifically it occurs after executing `./configure`

Many say `brew link berkeley-db4 --force` is required though it's not mentioned on build-osx.md and I did it.

#### If so, please list the steps to reproduce below:
```
brew install automake berkeley-db libtool boost --c++11 miniupnpc openssl pkg-config protobuf --c++11 qt5 libevent

git clone https://github.com/Bitcoin-ABC/bitcoin-abc.git
cd bitcoin-abc

./autogen.sh

brew link berkeley-db4 --force
./configure
```

### Expected behaviour
Installation is done without error

### Actual behaviour
```
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin ABC requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

### What version of bitcoin-abc are you using?
Latest version as of September 7th 

### Machine specs:
- OS:  macOS 10.13.6
- CPU: 2.2 GHz Intel Core i7
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 256GB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by axelay** [comment] 2018-09-18 21:52
I have the same issue on Ubuntu 16.04

**Comment by jasonbcox** [comment] 2018-09-18 23:01
I'm not sure about OSX, so I've marked the ticket as Help Wanted for those with OSX machines.  For Linux, following the libdb install instructions in doc/build-unix.md should work.

**Comment by Gerryrulz** [comment] 2018-09-28 11:08
I cannot get brew to work on Ubuntu properly nor can I compile Bitcoin ABC after downloading the Berkeley DB manually. This is so frustrating.

**Comment by axelay** [comment] 2018-09-28 11:10
Same issue as above - I have been fighting this for a while but nothing works.

**Comment by matiu** [comment] 2018-09-28 12:06
@axelay @Gerryrulz after running ./configure, check for configure.log for the precise error.

also, search your filesystem for the file 'libdb_cxx.h' and check its location

**Comment by axelay** [comment] 2018-09-28 12:32
@matiu thanks that put me on the right track.
I had the Berkeley DB 4.8 installed whereas the new code requires the latest version. I installed version 5.3.28 and it now compiles perfectly fine.

**Comment by matiu** [comment] 2018-09-28 12:42
@axelay you are welcome! I am glad you made it work, have fun!

**Comment by sriharikapu** [comment] 2018-11-08 11:30
I came across the same issue. I tried many times but I am not able to get over this issue. So what I did instead is to ignore this as a warning. It worked fine. Majority of the times the problem is with the configuration of berkeleydb.

**Comment by btqhd** [comment] 2019-01-19 21:02
Works on Debian with DB 4.8
../configure BDB_CFLAGS="-I${BDB_PREFIX}/include/" BDB_LIBS="-L${BDB_PREFIX}/lib/ -ldb_cxx-4.8"

**Comment by WillWammer** [comment] 2019-10-05 01:38
> Works on Debian with DB 4.8
> ../configure BDB_CFLAGS="-I${BDB_PREFIX}/include/" BDB_LIBS="-L${BDB_PREFIX}/lib/ -ldb_cxx-4.8"

Thanks! This worked!

**Comment by Dimianovic** [comment] 2021-07-23 06:34
I have the same issue (configure: error: libdb_cxx headers missing
), currently on linux mint. Anybody here, who can help me?

**Comment by Fabcien** [comment] 2021-07-23 07:09
@Dimianovic Please open a new issue and descbribe what command you run, the expected behavior and the actual output. Building using configure has been deprecated long time ago, I'm closing this issue.

**Closed by Fabcien** 2021-07-23 07:09 UTC
Labels: help wanted
