### ISSUE TITLE
estimatesmartfee ECONOMICAL warning

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Bitcoin-ABC/bitcoin-abc#142] opened 2017-12-28 04:37 UTC
regular estimatesmartfee works fine
```bash
bitcoin-cli estimatesmartfee 6
{
  "feerate": 0.00001000,
  "blocks": 6
}
```
but with ECONOMICAL mode it fails with warning!
```bash
bitcoin-cli estimatesmartfee 6 ECONOMICAL
error code: -1
error message:
estimatesmartfee nblocks

WARNING: This interface is unstable and may disappear or change!
.....
```
why is that? it should work, i believe...

**Comment by Vasiliy-Bondarenko** [comment] 2017-12-28 04:48
and on RPC calls i always get a warning no matter what mode i use or don't use at all. it always returns an error.

**Comment by OverlordQ** [comment] 2018-01-11 21:43
See #94

**Comment by jasonbcox** [comment] 2018-04-10 18:49
Closing as a duplicate of #94

**Closed by jasonbcox** 2018-04-10 18:49 UTC
Labels: duplicate
