### ISSUE TITLE
the node stop sync after i updated the noder v0.22.8

### ISSUE THREAD

**Issue by wallet-io** [Bitcoin-ABC/bitcoin-abc#419] opened 2020-12-03 05:33 UTC
i hava updated my node to v0.22.8
my node stop at 662858

how to resolve it , thanks

**Comment by ryan763** [comment] 2020-12-03 05:37
Download V0.22.8 BCHN version not BCHA.

https://download.bitcoinabc.org/bchn/0.22.8/linux/

**Comment by wallet-io** [comment] 2020-12-03 06:43
my bchn node  synced normally
bcha node stop

**Comment by wallet-io** [comment] 2020-12-03 06:45
![Uploading image.png…]()

**Comment by pmtoan** [comment] 2020-12-03 07:12
I run into the same problem. The BCHA node stops sync at block 662858. And the node is different with bitcoin ABC explorers as https://blockchair.com/bitcoin-abc or https://explorer.bitcoinabc.org/

**Comment by 90hacker** [comment] 2020-12-03 09:09
I run into the same problem.
```
2020-12-03T08:59:29Z UpdateTip: new best=000000000000000003e7ea491122031d5508d60ccd78665fd8000efb37eb1e85 height=662858 version=0x20800000 log2_work=88.406959 tx=295435324 date='2020-12-01T20:07:07Z' progress=0.998564 cache=26.9MiB(191805txo)
2020-12-03T08:59:29Z Park block 00000000000000000399b03a9ad823b883a46a7f97387d4d4c72397d33eb641f as it would cause a deep reorg.

```
No sync block information

**Comment by PiRK** [comment] 2020-12-03 16:06
Hi. Could you try the following commands:

```
bitcoin-cli parkblock 00000000000000000709b858a6a0c8610e604e77072ef4407763afb0780ce712
bitcoin-cli unparkblock 0000000000000000240e6f5b63a9f897c5d75e0eaba7f1a66a7828093115efb7
```
For the second command to unpark the correct chain, you can use the hash of a recent block found on https://explorer.bitcoinabc.org/
The one in my example is block 662930

**Comment by panlilu** [comment] 2020-12-04 03:55
Same problem.
@PiRK Tried these two commands, no effect.

**Comment by PiRK** [comment] 2020-12-04 07:44
You can try adding a few nodes that are on the correct chain, to receive new blocks.
`bitcoin cli addnode 51.89.98.76 add`
Try with 51.89.98.76, 139.99.121.170, 51.91.14.25, 158.69.25.42, 51.79.81.158

If it does not work, maybe your node banned too many honest nodes  while it was stuck on the wrong chain. You can try to stop your node, delete peers.dat and banlist.dat in the data directory, then restart. This will cause your node to restart with a fresh list of peers.

**Comment by pmtoan** [comment] 2020-12-04 10:42
I have resolved this problem by adding some whitelist nodes.

**Comment by quyse** [comment] 2020-12-09 07:17
FYI even freshly synchronized from scratch ABC full node (without whitelisting of whatever nodes) got stuck on this exact block, with similar log.

**Comment by PiRK** [comment] 2020-12-09 09:18
Thank you for your feedback.

This is a known problem, caused by the finalized block concept introduced in 0.18.5 (just after the BCH-BSV fork). It protects the network against deep reorg attacks in normal situation, but has the trade-off of causing problems during the initial block download when a significant fraction of the nodes are still stuck on the wrong chain. Your node received more than 10 block headers for the wrong chain first, causing it to later ignore the headers for the correct chain, even though the correct chain is  much longer.

The situation will improve as node operators continue switching to the correct chain. This will reduce the likelihood of receiving the wrong headers first. The next release of Bitcoin ABC will also fix the issue.

**Comment by BuyOwnEx** [comment] 2020-12-10 01:43
the same problem

**Comment by PiRK** [comment] 2020-12-10 16:52
If you need assistance to get back on the right chain, it would help if you shared the output of the following command:
`bitcoin-cli getchaintips`

That will tell you which chain is currently active (so we can park it), and which block on the correct chain is the latest one for which your node received headers. 
You can search for the block hash on explorer.bitcoinabc.org, if the explorer finds the block it means it is the correct chain.

**Comment by bagikh** [comment] 2020-12-15 00:29
Hello, I am trying to setup bitcoincash testnet node, however it wont sync to the bitcoin cash testnet explorer. 
Explorer url : https://explorer.bitcoin.com/tbch OR https://www.blockchain.com/explorer?view=bch-testnet

My bitcoin-cli getchaintips result is:
{
    "height": 1429951,
    "hash": "00000000014bda4d2ed4c17ff27f9c25b9808c31343951675eb673bbfd1aa2e8",
    "branchlen": 71925,
    "status": "headers-only"
  },
  {
    "height": 1421482,
    "hash": "00000000152d3f02662b10dc4555fe3edc66826c3e175e5fdf49b667966709f2",
    "branchlen": 63456,
    "status": "headers-only"
  },
  {
    "height": 1358026,
    "hash": "00000000000001cce0736ef90d60c55b988254a6da41cbc386e1036aba390e39",
    "branchlen": 0,
    "status": "active"
  }

As we can see, both hash of the heights of 1421482 and 1429951 are not synced to the explorer. I searched through internet and could not get any information. How I can sync my node to bitcoin-cash testnet explorer? Any help would be really appreciated.

**Comment by EternityTula** [comment] 2020-12-15 00:53
Same problem. Сan't sync either testnet or mainnet. :(
If someone could help with the correct config, we could add some hashrate to protect the network.

**Comment by Akonova1enko** [comment] 2020-12-15 19:31
![image](https://user-images.githubusercontent.com/16065186/102263357-ddef1700-3f1c-11eb-9692-325d357bfbc1.png)
same problem(

**Comment by PiRK** [comment] 2020-12-15 20:18
> ![image](https://user-images.githubusercontent.com/16065186/102263357-ddef1700-3f1c-11eb-9692-325d357bfbc1.png)
> same problem(

You are on the correct chain. You can see the block height and hash in the messages starting with "new best" and check it on the block explorer 
https://explorer.bitcoinabc.org/block-height/664877
The error you are seeing are caused by your nide taking to nodes on other chains.



> Same problem. Сan't sync either testnet or mainnet. :(
> If someone could help with the correct config, we could add some hashrate to protect the network.

Could you try again with the new release 0.22.9?

**Comment by Akonova1enko** [comment] 2020-12-15 21:52
but now it's syncing very slow((((
it is possible to fix somehow?
only ~43 blocks per few hours(
for scan 1 old block (664890) need 10 min(
![image](https://user-images.githubusercontent.com/16065186/102276942-41367480-3f30-11eb-91db-c9355ba5d201.png)
Thanks for fast reply!! @PiRK S

**Comment by bagikh** [comment] 2020-12-16 02:36
Does anybody know how to get test coin for bitcoin cash ABC? (not bchn)

**Comment by PiRK** [comment] 2020-12-16 14:41
> but now it's syncing very slow((((
> it is possible to fix somehow?
> only ~43 blocks per few hours(
> for scan 1 old block (664890) need 10 min(
> ![image](https://user-images.githubusercontent.com/16065186/102276942-41367480-3f30-11eb-91db-c9355ba5d201.png)
> Thanks for fast reply!! @PiRK S

At the time of your response, block 664890 was one of the latest block. Your node was up to date.

**Comment by Akonova1enko** [comment] 2020-12-16 15:25
> > but now it's syncing very slow((((
> > it is possible to fix somehow?
> > only ~43 blocks per few hours(
> > for scan 1 old block (664890) need 10 min
> 
> At the time of your response, block 664890 was one of the latest block. Your node was up to date.

hmmm, i check the latest block [here ](https://www.blockchain.com/bch/block/0000000000000000025992863ebe5b71204d931e15e820e914cc6a89736053f2)and there are 
more than 666167 bloks and my node scanned only 665009 blocks....
so from last my reply i recived only 665009-664846=163 new blocks(
it is ok? can you share good explorer for checking blocks pls?

we are crypto-wallet service and we need works node all time

**Comment by PiRK** [comment] 2020-12-16 15:37
OK, I see where the confusion is originating. There was a chain split on November 15th, so now there are two chains.

If you want to follow the ABC chain, you need to run the node that is currently called '_Bitcoin ABC (BCHA Network)'_. This node follows the same chain as the explorer at the following address: https://explorer.bitcoinabc.org/

If you want to follow the BCH chain, you need to download the software that is currently called _"Bitcoin ABC (BCHN Network)"_. 
This one follows the same chain as the explorer link that you shared.

There are more explanations here:
https://blog.bitcoinabc.org/2020/11/06/bitcoin-abc-will-support-both-bcha-and-bchn-after-the-chain-split/

And you can find the two versions of the software here:
https://www.bitcoinabc.org/releases/

**Comment by Akonova1enko** [comment] 2020-12-16 16:18
> OK, I see where the confusion is originating. There was a chain split on November 15th, so now there are two chains.
> 
> If you want to follow the ABC chain, you need to run the node that is currently called '_Bitcoin ABC (BCHA Network)'_. This node follows the same chain as the explorer at the following address: https://explorer.bitcoinabc.org/
> 
> If you want to follow the BCH chain, you need to download the software that is currently called _"Bitcoin ABC (BCHN Network)"_.
> This one follows the same chain as the explorer link that you shared.
> 
> There are more explanations here:
> https://blog.bitcoinabc.org/2020/11/06/bitcoin-abc-will-support-both-bcha-and-bchn-after-the-chain-split/
> 
> And you can find the two versions of the software here:
> https://www.bitcoinabc.org/releases/


ahhh! thank you for explain!!
the last one question: can i somehow change network in configuration  or while building app?
![image](https://user-images.githubusercontent.com/16065186/102375294-06354f00-3fcb-11eb-89f9-af8eb383fcb8.png)

**Comment by Fabcien** [comment] 2020-12-16 16:23
Yes `-DNETWORK_COMPATIBILITY=BCHN` is the flag you want.

**Comment by Akonova1enko** [comment] 2020-12-16 16:33
Perfect!! Thank you all ;)

**Comment by Fabcien** [comment] 2020-12-22 16:56
Closing, please reopen if you still have the issue with 0.22.9.

**Closed by Fabcien** 2020-12-22 16:56 UTC

**Comment by 1scrooge** [comment] 2020-12-29 08:08
I have the same problem with 0.22.9 
![image](https://user-images.githubusercontent.com/32951007/103269061-01f33380-49c6-11eb-8dc8-c20049d83dfb.png)
Last log:
```
bitcoin-abc-node    | 2020-12-29T08:01:50Z UpdateTip: new best=00000000000000003d620ffb7c8e1ae1f29b33a6ce195e1d631edb40e3bba042 height=662853 version=0x20800000 log2_work=88.406958 tx=295435318 date='2020-12-01T19:41:32Z' progress=0.974898 cache=414.0MiB(3158975txo)
bitcoin-abc-node    | 2020-12-29T08:01:50Z UpdateTip: new best=000000000000000023ef53c6761fa973b48fd6bde625963a4ec0a23857d1adec height=662854 version=0x3ea74000 log2_work=88.406959 tx=295435319 date='2020-12-01T19:42:08Z' progress=0.974898 cache=414.0MiB(3158977txo)
bitcoin-abc-node    | 2020-12-29T08:01:50Z UpdateTip: new best=000000000000000019a13423df242f53cdae0930cbcd2885a848dfb0c24801f6 height=662855 version=0x3fffe000 log2_work=88.406959 tx=295435320 date='2020-12-01T19:42:33Z' progress=0.974898 cache=414.0MiB(3158979txo)
bitcoin-abc-node    | 2020-12-29T08:01:50Z UpdateTip: new best=0000000000000000152dc967104199ee6719715177df31f2f4a859397ab098f5 height=662856 version=0x30b06000 log2_work=88.406959 tx=295435321 date='2020-12-01T19:43:32Z' progress=0.974899 cache=414.0MiB(3158981txo)
bitcoin-abc-node    | 2020-12-29T08:01:50Z UpdateTip: new best=000000000000000009ac51d476809a9d8c89e4650d985646c6cc696994b33ab6 height=662857 version=0x20a00000 log2_work=88.406959 tx=295435322 date='2020-12-01T19:45:12Z' progress=0.974900 cache=414.0MiB(3158983txo)
bitcoin-abc-node    | 2020-12-29T08:01:50Z UpdateTip: new best=000000000000000003e7ea491122031d5508d60ccd78665fd8000efb37eb1e85 height=662858 version=0x20800000 log2_work=88.406959 tx=295435324 date='2020-12-01T20:07:07Z' progress=0.974913 cache=414.0MiB(3158985txo)
bitcoin-abc-node    | 2020-12-29T08:02:32Z New outbound peer connected: version: 70015, blocks=667944, peer=67 (full-relay)
bitcoin-abc-node    | 2020-12-29T08:02:32Z New outbound peer connected: version: 70015, blocks=666620, peer=68 (full-relay)
bitcoin-abc-node    | 2020-12-29T08:03:25Z New outbound peer connected: version: 70015, blocks=667630, peer=71 (block-relay)
bitcoin-abc-node    | 2020-12-29T08:03:33Z New outbound peer connected: version: 70015, blocks=666620, peer=72 (full-relay)
bitcoin-abc-node    | 2020-12-29T08:04:37Z New outbound peer connected: version: 70015, blocks=667944, peer=75 (block-relay)
bitcoin-abc-node    | 2020-12-29T08:05:35Z New outbound peer connected: version: 70015, blocks=666620, peer=76 (full-relay)
bitcoin-abc-node    | 2020-12-29T08:07:37Z New outbound peer connected: version: 70015, blocks=666620, peer=79 (full-relay)

**Comment by M1neK1ng** [comment] 2023-04-30 03:34
im on the newest version after the split and it still happens.
its from a node that is injecting bad headers into the chain to syncing clients...
