### ISSUE TITLE
getrawtransaction RPC call broken in 0.18.8: confirmations, time and blocktime parameters missing in response

### ISSUE THREAD

**Issue by c0deright** [Bitcoin-ABC/bitcoin-abc#303] opened 2019-02-12 12:42 UTC
### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1. install abc-0.18.8 on linux
2. issue the following command: `bitcoin-cli getrawtransaction [someTXID from your wallet] true`

### Expected behaviour
JSON-Output should contain (in my case) the following data after `vin` and `vout`:

    (..)
    "vin": [
      (..)
    ],
    "vout": [
      (..)
    ],
    "blockhash": "000000000000000006b7e3fae05eda7bc578da13eb0220291b3668b1424b6353",
    "confirmations": 8899,
    "time": 1544630389,
    "blocktime": 1544630389

### Actual behaviour
JSON-Output is missing `confirmations`, `time` and `blocktime`:

    (..)
    "vin": [
      (..)
    ],
    "vout": [
      (..)
    ],
    "blockhash": "000000000000000006b7e3fae05eda7bc578da13eb0220291b3668b1424b6353"

### What version of bitcoin-abc are you using?
Bitcoin ABC Daemon version v0.18.7.0-g1da1ddd10, selfcompiled under Ubuntu 16.04 LTS

### Any extra information that might be useful in the debugging process.

* Works with abc-0.18.7
* The TXID in question is one of a watch-only address which was added to the wallet.dat some time ago (bitcoind running with `txindex=1`, of course)
* the node is only used to monitor certain watch-only addresses and has no private keys in wallet.dat (besides the one added automatically when wallet.dat was generated)

**Comment by c0deright** [comment] 2019-02-13 09:39
@deadalnix @jasonbcox 

Care to comment? This is a major showstopper for us.

**Comment by jnewbery** [comment] 2019-02-13 15:03
Hi @c0deright. I contribute to the Bitcoin Core project (https://github.com/bitcoin/bitcoin), which is the reference implementation of the Bitcoin protocol. Despite the confusing naming, this project (Bitcoin-ABC) and protocol (Bitcoin Cash) have nothing to do with Bitcoin.

The code in the commit that you reference is indeed taken from a contribution of mine, to Bitcoin Core, here: https://github.com/bitcoin/bitcoin/pull/8824/files. However, the backport was misapplied. Despite the comment being include (`Blockchain contextual information (confirmations and blocktime) is not  available to code in bitcoin-common, so we query them here and push the data into the returned UniValue.`), the code to do that wasn't.

The Bitcoin Cash maintainers are of course permitted to use my code (fully or partially), since it is licensed under the MIT license. That license states `THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED... IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY...`. Neither I nor the Bitcoin-ABC maintainers are 'the cause' of your showstopper.

Feel free to contribute a PR to Bitcoin-ABC fix this bug. Or not. I don't really care. But please don't summon me to this project again. Thanks!

**Comment by c0deright** [comment] 2019-02-13 15:29
Hi @jnewbery. Sorry, my mistake. I just looked at the commit history of that file. My bad.

**Comment by jasonbcox** [comment] 2019-02-14 00:02
@c0deright Thanks for reporting.  Indeed the backport was misapplied.  I'm working on a fix: https://reviews.bitcoinabc.org/D2546

**Comment by jasonbcox** [comment] 2019-02-14 01:16
It's been landed on master, so this fix will be available in the next release (0.19)

**Closed by jasonbcox** 2019-02-14 01:16 UTC
Labels: bug

**Comment by grittibaenz** [comment] 2019-02-15 09:46
@c0deright thanks for reporting, we ran into the same bug.
